{
 "title": "Veeam Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Job status",
   "type": "table",
   "gridPos": { "h": 16, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "time() - sort(veeam_br_jobs)" }
   ]
  },
  {
   "title": "Backup Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (veeam_br_jobs{type=\"backup\"})"
    }
   ]
  },
  {
   "title": "Replica Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (veeam_br_jobs{type=\"replica\"})"
    }
   ]
  },
  {
   "title": "Veeam Job throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (job_name) (veeam_br_jobs_throughput)",
     "legendFormat": "{{ job_name }}"
    }
   ]
  },
  {
   "title": "Veeam Job throughput (24h)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (job_name) (veeam_br_jobs_throughput)",
     "legendFormat": "{{ job_name }}"
    }
   ]
  }
 ]
}